version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/celfinder
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - celfinder-network
    restart: unless-stopped
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=celfinder
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - celfinder-network
    restart: unless-stopped
volumes:
  mongo-data:
networks:
  celfinder-network:
    driver: bridge